---

- name: Fail when deploy_local_public_key is none
  fail:
    msg: deploy_local_public_key must be set
  when: deploy_local_public_key is none

- name: Fail when deploy_hashed_password is none
  fail:
    msg: deploy_hashed_password must be set
  when: deploy_hashed_password is none

- name: Add groups
  group:
    name: "{{ item }}"
    state: present
  with_items: "{{ deploy_groups }}"

- name: Add users
  user:
    name: "{{ deploy_user }}"
    groups: "{{ deploy_groups }}"
    password: "{{ deploy_hashed_password }}"

- name: Add Authorized Key
  authorized_key:
    user:  "{{ deploy_user }}"
    state: present
    key: "{{ lookup('file', deploy_local_public_key) }}"
    comment: ansible
  when:
    - deploy_local_public_key is not none

- name: Add user to sudoers
  lineinfile:
    path: /etc/sudoers
    state: present
    line: "{{ deploy_user }} ALL=(ALL) NOPASSWD: ALL"
    validate: "/usr/sbin/visudo -cf %s"