---

- name: Remove Public Key
  local_action:
    module: file
    path: "{{ deploy_local_public_key }}"
    state: absent

- name: Generate Public Key
  local_action:
    module: openssl_publickey
    path: "{{ deploy_local_public_key }}"
    privatekey_path: "{{ deploy_local_private_key }}"
    state: present
    format: OpenSSH

- name: Add Authorized Key
  authorized_key:
    user:  "{{ deploy_user }}"
    state: present
    key: "{{ lookup('file', deploy_local_public_key) }}"
    comment: "{{ deploy_user }}.ansible"